install.packages("tidyverse")
install.packages("rmarkdown")
install.packages("httr")
install.packages("shinydashboard")
install.packages("janitor")
# install.packages("tidymodels")
# install.packages("wakefield")
# update.packages("caTools")
# update.packages("bitops")
# update.packages("rprojroot")
install.packages("devtools")
devtools::install_version("rmarkdown", version = "1.11", upgrade = "always")
devtools::install_github("btibert3/brock")
